### ISSUE TITLE
Server Side / nodejs Rendering

### ISSUE THREAD

**Issue by Xiphe** [trusktr/vue-web-component#1]
Hey there, nice project - great work!

Could I also pre-render the components in a node environment? 
Since you use skatejs under the hood, it should be possible to use [the ssr package of skate](https://github.com/skatejs/skatejs/tree/master/packages/ssr), right?

I'll update this issue when I had the time to test this out myself.

**Comment by gijo-varghese** [comment]
+1. Is there any chance for ssr?

**Comment by trusktr** [comment]
Hey guys, it depends what you mean by "SSR".

Custom Elements, by default, work with any sort of SSR. You just send HTML to the client, and, because browsers understand native HTML, the attributes get processed by the Custom Elements (in this case powered by Skate).

React/Vue/Angular, and other frameworks need special SSR tools because they aren't plain HTML. They need special data to be sent to the client, and a special tool that recreates the virtual trees that they work on.

So, in fact, no SSR is really needed. I don't even know what the Skate SSR package is really for, as I asked about in [this issue](https://github.com/skatejs/skatejs/issues/1356).

Your server just needs to send HTML, along with the script that creates your Web Components.

f.e., the actual payload from the server:

```html
<script src="your-application-bundle.js"></script>

<your-custom-element>
  ... etc ...
</your-custom-element>
```

**Comment by trusktr** [comment]
Posted that on the go. So to explain a little more, take this example, just a plain HTML response generated from the server side:

```html
<script src="your-application-bundle.js"></script>

<your-custom-element some-number="5" some-message="hello world">
  ... etc ...
</your-custom-element>
```

That HTML payload might be generated with regular server-side PHP, or something like Node.js EJS templates, etc, or Java JSP, nothing special or necessarily modern.

Then, `your-application-bundle.js` contains your app code (f.e. uses `vue-web-component`), and defines the custom elements. Thanks to SkateJS, and supposing that the `some-number` attribute expects a number and `some-message` expects a string, the custom elements will parse the attribute values and set the `someNumber` and `someMessage` properties on themselves with `typeof` of `number` and `string` respectively. (mapping array value and object value types is still [TODO](https://github.com/trusktr/vue-web-component/issues/5).

With all that said, you can still adopt a specific React SSR or Vue SSR tool (I mention React, because Web Components work anywhere, you're not limited to Vue). and render your application's initial payload that way, and these vue-web-components will still work. The custom elements will render just like any other HTML element would (with above mentioned processing of attribute value), but the difference here from traditional SSR is that the React or Vue components will be recreated and will take over the application.

And by

>  the React or Vue components will be recreated and will take over the application.

I don't mean the components wrapped inside the vue-web-components, I mean the outer components that your application is written with. The components will gain control of the elements that were sent in the HTML payload, and will dynamically start to pass new attributes/props to them as your end user start interacting.

So, there's actually two forms os SSR that can be at play:

1. traditional SSR, which is simply just sending an HTML payload, and custom elements on the page take over the elements once they are defined (f.e. by your app bundle),
2. Modern SSR with involves
  - sending an HTML payload like in the traditional SSR, in which case the same thing happens: your elements take over the elements.
  - reconstructing the component structure that was on the server-side, back on the client side, so that they can take over again, with the same state as they had on the server side.

---

So, ultimately, I'm not sure what Skate SSR is for, and I'd recommend using Vue SSR in Vue-based applications, but you can also use these vue-web-components in any application that uses any other framework (Angular, React, Preact, Moon.js, etc) and their respective SSR tools.

**Comment by Xiphe** [comment]
Hey @trusktr thanks for the elaborate response!

My question aimed at what you called "Modern SSR", so evaluating the custom elements on the server side so that they do not need `your-application-bundle.js` in the client to look as expected.

Benefits would be:

 - minimised time to first content
 - (no-js-)crawler support (facebook/twitter/other SE than google 🤷‍♂️)
 - potential use even without client side javascript (hypothetic, I know)

**Comment by trusktr** [comment]
Well, it's tricky. Many custom elements rely on JS to insert styling (f.e. CSS-in-JS libs at runtime), so relying purely on markup from the server to render exactly what should be displayed (without the app bundle) can be impossible depending on which custom elements you use in your app.

Seems like [declarative shadowdom](https://discourse.wicg.io/t/declarative-shadow-dom/1904/18) would be a starting point towards helping making this happen, but I can't yet see how it'd work without clientside JS (app bundle) in order for elements to do things that are pure-JS.

Another approach though, that will always work, is to use a headless browser and run the client-side code on the server, and just send a snapshot of the HTML, but even this is tricky, because depending on which elements you import into your app, you may not always know when they are done rendering, and may have to resort to a hacky timeout, short of modifying the 3rd-party code to emit events.

If we stick with pure Vue/React/Angular and builtin elements, then this guarantees that server-rendered HTML can be purely static, and in this case probably using Web Components isn't a fit. Much of Web Components APIs revolves around having client-side runtime JS code, and many custom elements simply will outright not work at all without it.

**Comment by trusktr** [comment]
Buuuuuut, that said, if we're using purely React/Vue-based _pure_ Web Components (pure means the same input for attributes always renders the same output), and no other types of Web Components, then it may be much more possible.

Good food for thought!

**Comment by trusktr** [comment]
Closing this, at least for now. It is possible to use existing SSR implementations of React/Vue/etc to render HTML elements (including the ones generated with vue-web-component).
